FROM maven:3.5-jdk-8-slim as mavenBuild
WORKDIR /usr/src/app/
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM openjdk:8-jre-slim as runtime
EXPOSE 8080
CMD [ "java","-jar","/usr/src/app/myapp.jar" ]
COPY --from=mavenBuild /usr/src/app/target/*.jar /usr/src/app/myapp.jar

